### ISSUE TITLE
Support for yaml?

### ISSUE THREAD

**Issue by cortopy** [kaasbaardje/block-comment-lines#2]
I just installed this package and I got the nice pop up message inviting me to submit an issue for YAML support. 

I was just wondering if this would be a possibility?

**Comment by MoonByteShaker** [comment]
Hi cortopy,

as the spec of YAML only mentions line comments, the only possibility would be to set a "#" in the begin of every selected line. 
Fortunately Atom already offers this functionality by the use of the command:

```
toggle-line-comments
```

I hope this will help you.
Greetings

**Comment by cortopy** [comment]
Working great that way. Thanks!
